python ASTARRodaje.py ./ASTAR-tests/mapa00.csv 1
python ASTARRodaje.py ./ASTAR-tests/mapa00.csv 2
python ASTARRodaje.py ./ASTAR-tests/mapa01.csv 1
python ASTARRodaje.py ./ASTAR-tests/mapa01.csv 2
python ASTARRodaje.py ./ASTAR-tests/mapa02.csv 1
python ASTARRodaje.py ./ASTAR-tests/mapa02.csv 2
python ASTARRodaje.py ./ASTAR-tests/mapa04.csv 2
python ASTARRodaje.py ./ASTAR-tests/mapa05.csv 2
python ASTARRodaje.py ./ASTAR-tests/mapa06.csv 1
python ASTARRodaje.py ./ASTAR-tests/mapa06.csv 2
python ASTARRodaje.py ./ASTAR-tests/mapa07.csv 1
python ASTARRodaje.py ./ASTAR-tests/mapa07.csv 2
python ASTARRodaje.py ./ASTAR-tests/mapa08.csv 1
python ASTARRodaje.py ./ASTAR-tests/mapa08.csv 2
python ASTARRodaje.py ./ASTAR-tests/mapa09.csv 1
python ASTARRodaje.py ./ASTAR-tests/mapa09.csv 2
python ASTARRodaje.py ./ASTAR-tests/mapa10.csv 1
python ASTARRodaje.py ./ASTAR-tests/mapa10.csv 2
python ASTARRodaje.py ./ASTAR-tests/mapa03.csv 2
python ASTARRodaje.py ./ASTAR-tests/mapa03.csv 1